# Generated by Django 3.0.8 on 2020-08-16 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpiapp', '0002_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
