# Generated by Django 3.1.1 on 2020-10-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='a@a.com', max_length=254)),
                ('employeeId', models.IntegerField()),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=20)),
                ('newpassword', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_email', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], default='female', max_length=6)),
                ('aadhar_card_number', models.CharField(max_length=16)),
                ('joining_date', models.DateField()),
                ('last_passout_year', models.IntegerField()),
                ('graduate_degree', models.CharField(blank=True, choices=[('bba', 'Bachelors of Business Admin.'), ('bsc', 'Bachelors of Science'), ('be', 'Bachelors of Engineering'), ('bca', 'Bachelors of Comp. Application'), ('bcom', 'Bachelors of Commerce'), ('bstat', 'Bachelors of Statistics'), ('b.tech', 'Bachelors of Technology'), ('others', 'Others'), ('not found', 'Not found')], default='others', max_length=10)),
                ('pg_degree', models.CharField(blank=True, choices=[('me', 'Master of Engineering'), ('mca', 'Master of Comp. Application'), ('mba', 'Master of Business Admin.'), ('mstat', 'Master of Stat'), ('not done', 'NA'), ('msc', 'Master of Science'), ('mca', 'Master of Computer Application'), ('others', 'others'), ('mtech', 'Master of Technology'), ('mcom', 'Master of Commerce')], default='not done', max_length=8)),
                ('graduate_stream', models.CharField(blank=True, choices=[('ECE', 'Electronice & Communication'), ('EE', 'Electrical Engineering'), ('CS', 'Computer Scienec'), ('NOT FOUND', 'Not Applicable'), ('No Stream', 'No Stream')], default='NOT FOUND', max_length=9)),
                ('pg_stream', models.CharField(blank=True, choices=[('ECE', 'Electronice & Communication'), ('EE', 'Electrical Engineering'), ('CS', 'Computer Scienec'), ('NOT FOUND', 'Not Applicable'), ('No Stream', 'No Stream')], default='NOT FOUND', max_length=9)),
                ('pg_yes_or_no', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('it_exp_months', models.IntegerField()),
                ('non_it_exp_months', models.IntegerField()),
                ('freshers', models.FloatField(choices=[(0.0, 'No'), (1.0, 'Yes'), (-1.0, '(Unknown)')], default=0.0)),
                ('marks_10th_percent', models.FloatField()),
                ('marks_12th_percent', models.FloatField()),
                ('graduate_cgpa', models.FloatField()),
                ('pg_cgpa', models.FloatField()),
                ('aptitude_score', models.IntegerField(default=0)),
                ('have_laptop', models.CharField(choices=[('Yes', 'YES'), ('No', 'NO'), ('NOT FOUND', 'NOT FOUND')], default='No', max_length=10)),
                ('state_location', models.CharField(blank=True, choices=[('West Bengal', 'West Bengal'), ('Bihar', 'Bihar'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Haryana', 'Haryana'), ('Odisa', 'Odisa'), ('Rajasthan', 'Rajasthan'), ('Karnataka', 'Karnataka'), ('Andhrapradesh', 'Andhra Pradesh'), ('Jharkhand', 'Jharkhand'), ('Delhi', 'Delhi'), ('Ladakh', 'Ladakh'), ('Punjab', 'Punjab'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Telangana', 'Telangana'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Maharashtra', 'Maharashtra'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Assam', 'Assam'), ('Odisha', 'Odisha')], max_length=30)),
                ('district_location', models.CharField(default='na', max_length=30)),
                ('purpuse_of_visit', models.CharField(choices=[('CLP', 'CLP'), ('Internship', 'Internship')], default='Internship', max_length=10)),
                ('college_name', models.CharField(blank=True, max_length=50)),
                ('pg_college', models.CharField(blank=True, max_length=50)),
                ('domain_interested', models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('Data Science', 'Data Science')], default='Python', max_length=15)),
                ('fathers_occupation', models.CharField(choices=[('PrivateBusiness', 'Private Business'), ('NotFound', 'Not Found'), ('Retired Govt. Employee', 'Retired Govt. Employee'), ('Retired in Defence', 'Retired in Defence')], default='NotFound', max_length=50)),
                ('mothers_occupation', models.CharField(choices=[('Teacher', 'Teacher'), ('Homemaker', 'Homemaker'), ('NotFound', 'Not Found')], default='NotFound', max_length=50)),
                ('no_of_siblings', models.CharField(default='NotFound', max_length=10)),
                ('siblings_working', models.CharField(default='NotFound', max_length=10)),
                ('domain_knowledge', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10)),
                ('previous_interviews_no', models.CharField(default='NotFound', max_length=10)),
                ('selected_interviews', models.CharField(default='NotFound', max_length=10)),
                ('reference_source', models.CharField(blank=True, choices=[('Facebook', 'Facebook'), ('LinkedIn', 'LinkedIn'), ('Consultancy', 'Consultancy'), ('Others', 'Others')], max_length=30)),
                ('status', models.CharField(choices=[('Called for HR Round', 'Called For HR Round'), ('HR Round Complete', 'HR Round Completed'), ('Direct joining', 'Direct Joining'), ('Confirmed but not join', 'Confirmed but not join')], max_length=100)),
                ('joined_yes_no', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('phone_number', models.IntegerField()),
                ('mail_id', models.EmailField(default='a@a.com', max_length=254)),
                ('feedback', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
