# Generated by Django 3.0.8 on 2020-08-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpproj', '0003_auto_20200822_0054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='identification',
            new_name='aadhar_card_no',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='year_pass',
            new_name='last_passout_year',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='email_add',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='identification_type',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='stream',
        ),
        migrations.AddField(
            model_name='registration',
            name='freshers',
            field=models.IntegerField(choices=[(None, '(Unknown)'), (0, 'No'), (1, 'Yes')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='graduate_degree',
            field=models.CharField(choices=[('bba', 'Bachelors of Business Admin.'), ('bse', 'Bachelors of Science'), ('be', 'Bachelors of Engineering'), ('bca', 'Bachelors of Comp. Application')], default='others', max_length=6),
        ),
        migrations.AddField(
            model_name='registration',
            name='graduate_stream',
            field=models.CharField(choices=[('ECE', 'Electronice & Communication'), ('EEE', 'Electrical Engineering'), ('CS', 'Computer Scienec')], default='NOT FOUND', max_length=8),
        ),
        migrations.AddField(
            model_name='registration',
            name='it_exp_months',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='not_it_exp_months',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='pg_degree',
            field=models.CharField(choices=[('me', 'Master of Engineering'), ('mca', 'Master of Comp. Application'), ('mba', 'Master of Business Admin.'), ('mstat', 'Master of Stat')], default='not done', max_length=6),
        ),
        migrations.AddField(
            model_name='registration',
            name='pg_stream',
            field=models.CharField(choices=[('ECE', 'Electronice & Communication'), ('EEE', 'Electrical Engineering'), ('CS', 'Computer Scienec')], default='NOT FOUND', max_length=8),
        ),
        migrations.AddField(
            model_name='registration',
            name='pg_yes_or_no',
            field=models.CharField(choices=[(None, '(Unknown)'), (0, 'No'), (1, 'Yes')], default='no', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='user_gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], default='m', max_length=1),
            preserve_default=False,
        ),
    ]
